import os
import sys
import time
import uuid
import sqlite3

sys.path.append(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
import config
from models import AgentState, ResultType, Severity

def run(state: AgentState) -> dict:
    start_time = time.time()
    exec_id = str(uuid.uuid4())
    
    business_context = state.get("business_context", {})
    tx_context = state.get("transaction_context", {})

    missing = (
        tx_context.get("pending_procurement")
        or business_context.get("missing_ingredients")
        or []
    )
    
    if not missing:
        if tx_context.get("workflow") == "RESTOCK":
            tx_context = {**tx_context, "status": "COMPLETED", "updated_at": time.time()}
        res = {
            "execution_id": exec_id,
            "service_name": "ProcurementService",
            "result_type": ResultType.SUCCESS,
            "severity": Severity.INFO,
            "user_message": "Tidak ada bahan baku yang perlu dipesan.",
            "developer_message": "No missing ingredients in business_context.",
            "payload": {"purchase_orders": []}
        }
        return {
            "services_results": [res],
            "business_context": {
                "procured_items": 0
            },
            "transaction_context": tx_context,
            "_metrics": {
                "agent": "ProcurementService",
                "latency_ms": (time.time() - start_time) * 1000,
                "decision": "NO_PROCUREMENT_NEEDED",
                "status": "OK",
                "execution_id": exec_id
            }
        }

    try:
        conn = sqlite3.connect(config.DB_PATH)
        c = conn.cursor()
        
        supplier_orders = {}
        
        for m in missing:
            ing_id = m["ingredient_id"]
            shortage = m["shortage"]
            
            c.execute("""
                SELECT supplier_id, supplier_name, price_per_unit_idr, min_order_quantity, lead_time_days
                FROM supplier 
                WHERE ingredient_id = ? 
                ORDER BY price_per_unit_idr ASC
            """, (ing_id,))
            
            suppliers = c.fetchall()
            
            if not suppliers:
                c.execute("""
                    SELECT supplier_id, supplier_name, price_per_unit_idr, min_order_quantity, lead_time_days
                    FROM supplier 
                    LIMIT 1
                """)
                suppliers = c.fetchall()

            if suppliers:
                best_sup = suppliers[0]
                sup_id = best_sup[0]
                price = best_sup[2] if best_sup[2] else 50000.0
                order_qty = max(shortage, best_sup[3])
                
                if sup_id not in supplier_orders:
                    supplier_orders[sup_id] = {
                        "supplier_name": best_sup[1],
                        "lead_time": best_sup[4],
                        "items": []
                    }
                    
                supplier_orders[sup_id]["items"].append({
                    "ingredient_id": ing_id,
                    "ingredient_name": m.get("ingredient_name", ing_id),
                    "order_qty": order_qty,
                    "estimated_cost": order_qty * price
                })
        
        import datetime
        now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        purchase_orders_created = []
        
        for sup_id, data in supplier_orders.items():
            po_id = str(uuid.uuid4())
            po_no = f"PO-{datetime.datetime.now().strftime('%Y%m%d')}-{str(uuid.uuid4())[:4].upper()}"
            
            c.execute("""
                INSERT INTO purchase_orders (
                    id, po_number, supplier_id, status, expected_arrival, 
                    approved_by, remarks, created_at, updated_at
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
            """, (po_id, po_no, sup_id, 'PENDING', None, 'AUTO', 'Generated by AI', now, now))
            
            for item in data["items"]:
                c.execute("""
                    INSERT INTO purchase_order_items (
                        id, purchase_order_id, ingredient_id, order_qty, estimated_cost, unit
                    ) VALUES (?, ?, ?, ?, ?, ?)
                """, (str(uuid.uuid4()), po_id, item["ingredient_id"], item["order_qty"], item["estimated_cost"], 'ml'))
                
            purchase_orders_created.append(po_no)
        
        conn.commit()
        conn.close()
        
        latency = (time.time() - start_time) * 1000
        
        res = {
            "execution_id": exec_id,
            "service_name": "ProcurementService",
            "result_type": ResultType.SUCCESS,
            "severity": Severity.INFO,
            "user_message": f"Telah dibuat {len(purchase_orders_created)} pesanan pembelian (PO) untuk bahan baku yang kurang.",
            "developer_message": "Purchase orders generated successfully.",
            "payload": {"purchase_orders": purchase_orders_created}
        }
        
        return {
            "services_results": [res],
            "business_context": {
                "procured_items": len(purchase_orders_created)
            },
            "transaction_context": _complete_restock_transaction(state),
            "_metrics": {
                "agent": "ProcurementService",
                "latency_ms": latency,
                "decision": "ORDERS_GENERATED",
                "status": "OK",
                "execution_id": exec_id
            }
        }

    except Exception as e:
        if 'conn' in locals():
            try: conn.rollback()
            except: pass
        if 'conn' in locals():
            try: conn.close()
            except: pass
            
        latency = (time.time() - start_time) * 1000
        res = {
            "execution_id": exec_id,
            "service_name": "ProcurementService",
            "result_type": ResultType.ERROR,
            "severity": Severity.ERROR,
            "user_message": "Mohon maaf, saat ini sistem gagal memproses pemesanan bahan baku.",
            "developer_message": f"SQLite Error: {str(e)}",
            "payload": {}
        }
        return {
            "services_results": [res],
            "_metrics": {
                "agent": "ProcurementService",
                "latency_ms": latency,
                "decision": "Error",
                "status": "ERROR",
                "execution_id": exec_id
            }
        }

def _complete_restock_transaction(state: AgentState) -> dict:
    tx_context = state.get("transaction_context", {})
    if tx_context.get("workflow") == "RESTOCK":
        completed = {**tx_context, "status": "COMPLETED", "updated_at": time.time()}
        completed.pop("pending_procurement", None)
        return completed
    return tx_context
