from enum import Enum

class Action(str, Enum):
    CHECK_PRICE = "CHECK_PRICE"
    CHECK_STOCK = "CHECK_STOCK"
    CREATE_ORDER = "CREATE_ORDER"
    PRODUCE_ITEM = "PRODUCE_ITEM"
    PROCURE_ITEM = "PROCURE_ITEM"
    CHECK_REPORT = "CHECK_REPORT"
    COORDINATE_RESPONSE = "COORDINATE_RESPONSE"
