from enum import Enum

class ResultType(str, Enum):
    SUCCESS = "SUCCESS"
    WARNING = "WARNING"
    CLARIFICATION = "CLARIFICATION"
    ERROR = "ERROR"

class Severity(str, Enum):
    INFO = "INFO"
    WARNING = "WARNING"
    ERROR = "ERROR"
    CRITICAL = "CRITICAL"

class InventoryStatus(str, Enum):
    AVAILABLE = "AVAILABLE"
    LOW_STOCK = "LOW_STOCK"
    OUT_OF_STOCK = "OUT_OF_STOCK"
    NOT_FOUND = "NOT_FOUND"
    ERROR = "ERROR"

class ProductionStatus(str, Enum):
    READY = "READY"
    INSUFFICIENT_INGREDIENTS = "INSUFFICIENT_INGREDIENTS"
    FORMULA_NOT_FOUND = "FORMULA_NOT_FOUND"
    NOT_REQUIRED = "NOT_REQUIRED"

class WorkflowStatus(str, Enum):
    START = "START"
    COLLECTING_INFORMATION = "COLLECTING_INFORMATION"
    PROCESSING = "PROCESSING"
    WAITING_USER_INPUT = "WAITING_USER_INPUT"
    EXECUTING_SERVICE = "EXECUTING_SERVICE"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"

class WorkflowEvent(str, Enum):
    PURCHASE_INTENT = "PURCHASE_INTENT"
    RESTOCK_INTENT = "RESTOCK_INTENT"
    INFO_PROVIDED = "INFO_PROVIDED"
    CONFIRM = "CONFIRM"
    REJECT = "REJECT"
    PAYMENT_SELECTED = "PAYMENT_SELECTED"
    CHANGE_VARIANT = "CHANGE_VARIANT"
    CHANGE_QTY = "CHANGE_QTY"
    ROLLBACK = "ROLLBACK"
    TIMEOUT = "TIMEOUT"
    UNKNOWN = "UNKNOWN"
